### PR TITLE
update mkdocs.yml

### PR DESCRIPTION
**Pull request by Sn1kk3r5**
This change brings the same look and feel like in the english version.

@buchen 
This is my first try of PR with git desktop. There is a .gitignore file attached, unfortunately I have no idea how to delete it.
Any hint is highly appreciated.

As I'm not pro on github i tried a couple things. In addition to my folk I created a dev branch --> merged this into my folk and created a PR than. But now it seems my PR includes 2 seperate changes which wasn't my intention! How can I improve this?

Some further information, and case you missed the the tread in the forum. Joachim and myself will take care for the german manual as the english one is far ahead. So there will be a bunch of PR's in the near future.

Cheers

### CODE REVIEW

**Comment by Sn1kk3r5** [comment]
Hi Hugo,

thanks for the merge.

What’s the best possible way to get in touch with you directly?

Cheers
Cris

Von: hug-sch ***@***.***>
Gesendet: Wednesday, 24 April 2024 12:57
An: portfolio-performance/portfolio-help ***@***.***>
Cc: Marmol Carmona, Christopher Lee ***@***.***>; Author ***@***.***>
Betreff: Re: [portfolio-performance/portfolio-help] update mkdocs.yml (PR #35)


Merged #35<https://github.com/portfolio-performance/portfolio-help/pull/35> into master.

**Comment by hug-sch** [comment]
Hi Cris,

Maybe the easiest way is through e-mail? You can find me at ***@***.***

Kind regards
Hugo
________________________________
From: Sn1kk3r5 ***@***.***>
Sent: Tuesday, April 23, 2024 15:28
To: portfolio-performance/portfolio-help ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [portfolio-performance/portfolio-help] update mkdocs.yml (PR #35)


This change brings the same look and feel like in the english version.

@buchen<https://github.com/buchen>
This is my first try of PR with git desktop. There is is .gitignore file attached, unfortunately I have no idea how to delete it.
Any hint is highly appreciated.

Some further information, and case you missed the the tread in the forum. Joachim and myself will take care for the german manual as the english one is far ahead. So there will be a bunch of PR's in the near future.

Cheers

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/portfolio-performance/portfolio-help/pull/35

Commit Summary

  *   5b11c44<https://github.com/portfolio-performance/portfolio-help/pull/35/commits/5b11c449397267cbedd3e96982e0b887b2e81d7e> update mkdocs.yml
  *   1aceaa0<https://github.com/portfolio-performance/portfolio-help/pull/35/commits/1aceaa0f63abdf1e18e4888e384ff8b39f766e15> Merge pull request #1 from Sn1kk3r5/dev

File Changes

(2 files<https://github.com/portfolio-performance/portfolio-help/pull/35/files>)

  *   M .gitignore<https://github.com/portfolio-performance/portfolio-help/pull/35/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947> (1)
  *   M config/de/mkdocs.yml<https://github.com/portfolio-performance/portfolio-help/pull/35/files#diff-fc6b3a8c0e6ede0481ad25b410b525373bea465c2a33540e32e9946367b81476> (46)

Patch Links:

  *   https://github.com/portfolio-performance/portfolio-help/pull/35.patch
  *   https://github.com/portfolio-performance/portfolio-help/pull/35.diff

**Comment by Sn1kk3r5** [comment]
Unfortunately git blinds the email address.

All I see is ***@***.***  ☹

Cheers
Cris

Von: hug-sch ***@***.***>
Gesendet: Wednesday, 24 April 2024 15:16
An: portfolio-performance/portfolio-help ***@***.***>
Cc: Marmol Carmona, Christopher Lee ***@***.***>; Author ***@***.***>
Betreff: Re: [portfolio-performance/portfolio-help] update mkdocs.yml (PR #35)

Hi Cris,

Maybe the easiest way is through e-mail? You can find me at ***@***.***<mailto:***@***.***>

Kind regards
Hugo
________________________________
From: Sn1kk3r5 ***@***.***<mailto:***@***.***>>
Sent: Tuesday, April 23, 2024 15:28
To: portfolio-performance/portfolio-help ***@***.***<mailto:***@***.***>>
Cc: Subscribed ***@***.***<mailto:***@***.***>>
Subject: [portfolio-performance/portfolio-help] update mkdocs.yml (PR #35)


This change brings the same look and feel like in the english version.

@buchen<https://github.com/buchen>
This is my first try of PR with git desktop. There is is .gitignore file attached, unfortunately I have no idea how to delete it.
Any hint is highly appreciated.

Some further information, and case you missed the the tread in the forum. Joachim and myself will take care for the german manual as the english one is far ahead. So there will be a bunch of PR's in the near future.

Cheers

________________________________
You can view, comment on, or merge this pull request online at:

https://github.com/portfolio-performance/portfolio-help/pull/35

Commit Summary

* 5b11c44<https://github.com/portfolio-performance/portfolio-help/pull/35/commits/5b11c449397267cbedd3e96982e0b887b2e81d7e> update mkdocs.yml
* 1aceaa0<https://github.com/portfolio-performance/portfolio-help/pull/35/commits/1aceaa0f63abdf1e18e4888e384ff8b39f766e15> Merge pull request #1 from Sn1kk3r5/dev

File Changes

(2 files<https://github.com/portfolio-performance/portfolio-help/pull/35/files>)

* M .gitignore<https://github.com/portfolio-performance/portfolio-help/pull/35/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947> (1)
* M config/de/mkdocs.yml<https://github.com/portfolio-performance/portfolio-help/pull/35/files#diff-fc6b3a8c0e6ede0481ad25b410b525373bea465c2a33540e32e9946367b81476> (46)

Patch Links:

* https://github.com/portfolio-performance/portfolio-help/pull/35.patch
* https://github.com/portfolio-performance/portfolio-help/pull/35.diff

**Comment by buchen** [comment]
> Unfortunately git blinds the email address.

you can send me an email at portfolio dot performance dot help at gmail dot com.
You get in touch with Hugo at hug-sch at outlook dot com.


> This is my first try of PR with git desktop. There is a .gitignore file attached, unfortunately I have no idea how to delete it.
Any hint is highly appreciated.

Personally, I am not using Github Desktop because it confuses me.
But generally, one can pick (part of) a change and say "revert". That creates a second commit undoing the .gitignore.
You can then "squash" those commits into one and "force push" into the same branch (which updates the pull request).

While all of this sounds natural to a developer, it might not be so intuitive for non-developers.
I'd be happy to a virtual meeting to discuss how to best organize this.  Drop me an email and we find a time which makes sense.

> Some further information, and case you missed the the tread in the forum. Joachim and myself will take care for the german manual as the english one is far ahead. So there will be a bunch of PR's in the near future.

:-)

**Pull request merged**
