### PR TITLE
Hack quote feed

### PR DESCRIPTION
**Pull request by flywire**
Hack the XML file directly to add the Quote Feed: use a text editor replace to add the Quote Feed.

### CODE REVIEW

**Comment by flywire** [comment]
> This is a terrible duplication of git functionality and should be removed.

https://github.com/portfolio-performance/portfolio-help/blob/master/todo/todo.md#2023-09-13-suggestion-implemented
> The mkdocs material frontmatter can contain several key-value pairs...

I'm not aware of this functionality. Did I miss it or does it need highlighting?

**Comment by hug-sch** [comment]
> This is a terrible duplication of git functionality and should be removed.

Agree. Meanwhile I found a plugin https://github.com/timvink/mkdocs-git-revision-date-localized-plugin that works well with the Material theme. It adds the last update date at the bottom of the page.

**Comment by hug-sch** [comment]
> Hack the XML file directly to add the Quote Feed: use a text editor replace to add the Quote Feed.

Have not the faintest idea what you are talking about.

**Review by hug-sch — APPROVED** [review]
I've merged your "quote-feed.md" page. I see that you have added your image into the local folder. This was my first workflow (keeping the images close to the place they are used). Later-on I've changed to a more central image folder (some arguments are given in the contributing.md but it seems more difficult after a few months and piling-up images ). So, I'm not sure which approach is the best.

**Pull request merged**
